<#
.SYNOPSIS
  Builds the static frontend bundle that CloudFront serves.

.DESCRIPTION
  Copies web-ui/ to web-ui-dist/ and writes config.js from the deployed stack
  outputs, so the API URL and Cognito IDs are never hardcoded in source.

  web-ui/ is the single source of truth. web-ui-dist/ is generated and
  gitignored — never edit it directly.

.PARAMETER StackName
  CloudFormation stack to read outputs from. Defaults to VaioStack.

.PARAMETER Region
  AWS region holding the stack. Defaults to us-east-1.

.PARAMETER SkipConfig
  Copy the static files but do not query AWS or regenerate config.js. Useful
  before the first deploy, when no stack outputs exist yet.
#>
[CmdletBinding()]
param(
    [string]$StackName = "VaioStack",
    [string]$Region = "us-east-1",
    [switch]$SkipConfig
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$sourceDir = Join-Path $repoRoot "web-ui"
$distDir = Join-Path $repoRoot "web-ui-dist"

if (-not (Test-Path $sourceDir)) {
    throw "Frontend source not found: $sourceDir"
}

Write-Host "Staging frontend into $distDir" -ForegroundColor Cyan
if (Test-Path $distDir) {
    Remove-Item -Recurse -Force $distDir
}
New-Item -ItemType Directory -Force -Path $distDir | Out-Null

Get-ChildItem -Path $sourceDir -File |
    Where-Object { $_.Name -notin @("config.js", ".env", ".env.example") } |
    ForEach-Object { Copy-Item $_.FullName (Join-Path $distDir $_.Name) -Force }

# PowerShell 5.1's Set-Content -Encoding utf8 emits a byte-order mark. A BOM at the
# start of a script file is tolerated by browsers but is still junk in a generated
# artefact, so write UTF-8 without one explicitly.
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
function Write-TextFile {
    param([string]$Path, [string]$Content)
    [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
}

if ($SkipConfig) {
    Write-Host "Skipping config.js generation (-SkipConfig)." -ForegroundColor Yellow
    # A placeholder keeps the <script> tag from 404ing during local preview.
    Write-TextFile (Join-Path $distDir "config.js") `
        "// Placeholder. Run build-frontend.ps1 without -SkipConfig after deploying.`n"
}
else {
    Write-Host "Reading outputs from stack $StackName ($Region)" -ForegroundColor Cyan
    $outputsJson = aws cloudformation describe-stacks `
        --stack-name $StackName `
        --region $Region `
        --query "Stacks[0].Outputs" `
        --output json
    if ($LASTEXITCODE -ne 0) {
        throw "Could not read stack outputs for $StackName. Deploy the stack first, or pass -SkipConfig."
    }

    $outputs = @{}
    foreach ($entry in ($outputsJson | ConvertFrom-Json)) {
        $outputs[$entry.OutputKey] = $entry.OutputValue
    }

    foreach ($required in @("ApiGatewayURL", "UserPoolId", "UserPoolClientId")) {
        if (-not $outputs.ContainsKey($required)) {
            throw "Stack output '$required' is missing; cannot generate config.js."
        }
    }

    # ApiGatewayURL comes back as https://<id>.execute-api.<region>.amazonaws.com/prod/
    $apiBase = $outputs["ApiGatewayURL"].TrimEnd("/")

    # Read from the stack rather than assumed, so the sign-in screen always matches
    # what the pool permits. Absent output is treated as closed: failing safe here
    # means at worst the Sign up link is hidden when it could have been shown.
    $allowSelfSignUp = 'false'
    if ($outputs.ContainsKey("SelfSignUpEnabled") -and $outputs["SelfSignUpEnabled"] -eq 'true') {
        $allowSelfSignUp = 'true'
    }

    # ASCII only: this file is machine-generated and there is no reason to risk an
    # encoding round trip over a typographic dash.
    $configLines = @(
        "// Generated by scripts/build-frontend.ps1. Do not edit by hand.",
        "// Source of truth is the CloudFormation outputs of stack $StackName.",
        "window.__VAIO_CONFIG = {",
        "  apiUrl: '$apiBase/api',",
        "  cognitoUserPoolId: '$($outputs["UserPoolId"])',",
        "  cognitoClientId: '$($outputs["UserPoolClientId"])',",
        "  region: '$Region',",
        "  allowSelfSignUp: $allowSelfSignUp,",
        "};"
    )
    Write-TextFile (Join-Path $distDir "config.js") (($configLines -join "`n") + "`n")
    Write-Host "  API:          $apiBase/api" -ForegroundColor DarkGray
    Write-Host "  Pool:         $($outputs["UserPoolId"])" -ForegroundColor DarkGray
    Write-Host "  Self sign-up: $allowSelfSignUp" -ForegroundColor DarkGray
}

$files = (Get-ChildItem -Path $distDir -File | Measure-Object).Count
Write-Host "Frontend bundle ready: $distDir ($files files)" -ForegroundColor Green
