<#
.SYNOPSIS
  Builds the static frontend bundle that CloudFront serves.

.DESCRIPTION
  Copies web-ui/ to web-ui-dist/ and writes config.js from the deployed stack
  outputs, so the API URL and Cognito IDs are never hardcoded in source.

  web-ui/ is the single source of truth. web-ui-dist/ is generated and
  gitignored — never edit it directly.

.PARAMETER StackName
  CloudFormation stack to read outputs from. Defaults to VaioStack.

.PARAMETER Region
  AWS region holding the stack. Defaults to us-east-1.

.PARAMETER SkipConfig
  Copy the static files but do not query AWS or regenerate config.js. Useful
  before the first deploy, when no stack outputs exist yet.
#>
[CmdletBinding()]
param(
    [string]$StackName = "VaioStack",
    [string]$Region = "us-east-1",
    [switch]$SkipConfig
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$sourceDir = Join-Path $repoRoot "web-ui"
$distDir = Join-Path $repoRoot "web-ui-dist"

if (-not (Test-Path $sourceDir)) {
    throw "Frontend source not found: $sourceDir"
}

Write-Host "Staging frontend into $distDir" -ForegroundColor Cyan
if (Test-Path $distDir) {
    Remove-Item -Recurse -Force $distDir
}
New-Item -ItemType Directory -Force -Path $distDir | Out-Null

Get-ChildItem -Path $sourceDir -File |
    Where-Object { $_.Name -notin @("config.js", ".env", ".env.example") } |
    ForEach-Object { Copy-Item $_.FullName (Join-Path $distDir $_.Name) -Force }

if ($SkipConfig) {
    Write-Host "Skipping config.js generation (-SkipConfig)." -ForegroundColor Yellow
    # A placeholder keeps the <script> tag from 404ing during local preview.
    "// Placeholder — run build-frontend.ps1 without -SkipConfig after deploying." |
        Set-Content -Path (Join-Path $distDir "config.js") -Encoding utf8
}
else {
    Write-Host "Reading outputs from stack $StackName ($Region)" -ForegroundColor Cyan
    $outputsJson = aws cloudformation describe-stacks `
        --stack-name $StackName `
        --region $Region `
        --query "Stacks[0].Outputs" `
        --output json
    if ($LASTEXITCODE -ne 0) {
        throw "Could not read stack outputs for $StackName. Deploy the stack first, or pass -SkipConfig."
    }

    $outputs = @{}
    foreach ($entry in ($outputsJson | ConvertFrom-Json)) {
        $outputs[$entry.OutputKey] = $entry.OutputValue
    }

    foreach ($required in @("ApiGatewayURL", "UserPoolId", "UserPoolClientId")) {
        if (-not $outputs.ContainsKey($required)) {
            throw "Stack output '$required' is missing; cannot generate config.js."
        }
    }

    # ApiGatewayURL comes back as https://<id>.execute-api.<region>.amazonaws.com/prod/
    $apiBase = $outputs["ApiGatewayURL"].TrimEnd("/")

    $configLines = @(
        "// Generated by scripts/build-frontend.ps1 — do not edit by hand.",
        "// Source of truth is the CloudFormation outputs of stack $StackName.",
        "window.__VAIO_CONFIG = {",
        "  apiUrl: '$apiBase/api',",
        "  cognitoUserPoolId: '$($outputs["UserPoolId"])',",
        "  cognitoClientId: '$($outputs["UserPoolClientId"])',",
        "  region: '$Region',",
        "};"
    )
    $configLines -join "`n" | Set-Content -Path (Join-Path $distDir "config.js") -Encoding utf8
    Write-Host "  API:  $apiBase/api" -ForegroundColor DarkGray
    Write-Host "  Pool: $($outputs["UserPoolId"])" -ForegroundColor DarkGray
}

$files = (Get-ChildItem -Path $distDir -File | Measure-Object).Count
Write-Host "Frontend bundle ready: $distDir ($files files)" -ForegroundColor Green
